alias aliassave='alias > /home/jagipson/.bash_aliases'
alias gglad='git log --graph --all --decorate'
alias l.='ls -d .* --color=tty'
alias lad='ls -A --color=always -lt --file-type --group-directories-first -h --time-style="+ $(tput bold; tput setf 0)mtime:%a %y-%m-%d %R %Z$(tput sgr0) "'
alias ll='ls -l --color=tty --time-style=long-iso'
alias ls='ls --color=tty --time-style=long-iso'
alias malias='ypcat -k mail.mraliases'
alias mutt='TERM=xterm-256color /home/jagipson/bin/mutt'
alias t='task ready'
alias vi='vim'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias abdicate='coronate -u'
